version: '3'

services:
  moneyappbackend:
    image: node:carbon-alpine
    volumes:
    - ./:/app
    working_dir: /app
    links:
    - mongodb
    command: ["npm", "start"]
    environment:
      MONGODB_URL: "mongodb://mongodb:27017"
    ports:
    - 4000:4000
    networks:
    - bridge
  mongodb:
    image: mongo:3.6.6
    networks:
    - bridge
networks:
  bridge:
    driver: bridge

