version: '2'
services:
  api:
    image: node:carbon-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    command: ["npm", "start"]
  mongodb:
      image: mongo:3.6
      ports:
        - "27017:27017"
