# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-backend:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.6.0

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: npm install
      - run: ./Backend/build.sh

  package-backend:
    docker:
      - image: circleci/node:11.6.0

    steps:
      - setup_remote_docker:
                docker_layer_caching: true
      - checkout
      - run: npm install

      - run: |
          cd Backend
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   $DOCKER_REPO/$DOCKER_IMAGENAME:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_REPO/$DOCKER_IMAGENAME:$TAG

workflows:
  version: 2
  workflow:
    jobs:
    - build-backend
    - approve:
        type: approval
        filters:
          branches:
            only:
              - master
        requires:
          - build-backend
    - package-backend:
        filters:
          branches:
            only:
              - master
        requires:
          - approve
